"use client";
import type { Metadata } from "next";
import "./globals.css";
import "./ui/clientStyles.css";
import { inter } from "@/app/ui/fonts";
import ClientProvider from "./ClientProvider";
import ReduxProvider from "./providers/ReduxProvider";
import { ProfileContextProvider } from "./utils/useProfileContext";

// export const metadata: Metadata = {
//   title: "Chaturvarnam",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ReduxProvider>
          <ClientProvider><ProfileContextProvider>{children}</ProfileContextProvider></ClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
