name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies (with dev)
        run: npm ci

      - name: Promote Next.js to runtime dependency for Azure
        shell: bash
        run: |
          node -e "const fs=require('fs');const p=JSON.parse(fs.readFileSync('package.json','utf8'));if(p.devDependencies&&p.devDependencies.next){p.dependencies=p.dependencies||{};p.dependencies.next=p.devDependencies.next;delete p.devDependencies.next;fs.writeFileSync('package.json',JSON.stringify(p,null,2)+'\n');console.log('Moved next to dependencies for runtime.');} else {console.log('next not found in devDependencies or already present in dependencies.');}"

      - name: Build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run build --if-present

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: |
            .
            !**/.git/**
            !**/node_modules/**
            !**/.next/cache/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C970629CE86E4825AB6308142C9AFE83 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_68E8E0F63AC34F1DB979CBDE1389E050 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CA04C0473A5C4BA5836AD6C29F6B5609 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chaturvarnam'
          slot-name: 'Production'
          package: .
