name: Build and deploy Node.js app to Azure Web App - chaturvarnam-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Create production node_modules (without dev dependencies)
        run: |
          npm ci --only=production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: List files for debugging
        run: ls -la

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9F87E7FC8DA04BAAB7E52CCF65A615B2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7163375029D84264BAAC59D1BAAF0FD9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_14698773CD9B4B5996174A763045292D }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chaturvarnam-ui'
          slot-name: 'Production'
          package: .
